### ISSUE TITLE
fix mobile view

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#100]
1. full view of graph/chart:
![Screenshot_20191016-125819_Chrome](https://user-images.githubusercontent.com/863519/66909951-5c4ce200-f016-11e9-81de-9e9c1142fc8c.jpg)
![Screenshot_20191016-125905_Chrome](https://user-images.githubusercontent.com/863519/66910148-adf56c80-f016-11e9-8afd-530feab4b818.jpg)

2. full view of table in modal:
![Screenshot_20191016-125846_Chrome](https://user-images.githubusercontent.com/863519/66910130-a6ce5e80-f016-11e9-9bc8-8f49b6d47ab7.jpg)

3. Polls: table view
![Screenshot_20191016-130131_Chrome](https://user-images.githubusercontent.com/863519/66910198-c5345a00-f016-11e9-95c3-0dcca1daa75e.jpg)

4. Executive Votes: table view
![Screenshot_20191016-130024_Chrome](https://user-images.githubusercontent.com/863519/66910166-b9489800-f016-11e9-898e-ea7f449dc68c.jpg)

5. 'Last month' is not completely visible:
![Screenshot_20191016-125833_Chrome](https://user-images.githubusercontent.com/863519/66910017-77b7ed00-f016-11e9-8b64-2d25ba15279d.jpg)

**Comment by matextrem** [comment]
Done
