### ISSUE TITLE
Executive Vote Details: Top Supporters - see description

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#110]
open app
go to Executive Votes
open some Vote and look at Top Supporters section
Result:
![Screen Shot 2019-10-16 at 5 49 45 PM](https://user-images.githubusercontent.com/863519/66930710-aac1a700-f03d-11e9-8860-1505ec1596fd.png)

Expected:
![Screen Shot 2019-10-16 at 5 51 14 PM](https://user-images.githubusercontent.com/863519/66930748-b57c3c00-f03d-11e9-811f-d79764cbc283.png)

1. make address link to etherscan
2. show all supporters

**Comment by matextrem** [comment]
1. It is already implemented.
2. It is like a podium.
