### ISSUE TITLE
Dashboard: Rename existing tiles

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#146]
https://docs.google.com/document/d/1xku698E6fp8MVvECJkXYltXHXrG6JrE-Nb-huY5Xiig/edit#heading=h.plefec4adwa8

**Comment by tatyanakurinskaya** [comment]
please update:
1. Number of voters vs Total MKR staked ---> Number of Voters vs. Total MKR Staked
2. Executive Votes - Time Taken To Pass ---> Executive Time to Pass
3. Most Recent Polls ---> Recent Polls
4. Total Votes vs Polls ---> Total Votes
