### ISSUE TITLE
Dashboard: Reorganize tiles in categories

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#147]
From the [spec document](https://docs.google.com/document/d/1xku698E6fp8MVvECJkXYltXHXrG6JrE-Nb-huY5Xiig/edit#heading=h.z2d5uv3kmmo6)

> Display all metrics divided into the categories below. Note I’m not sure how best to layout this page, I’ll leave that up to you guys. Maybe a 2x2 grid per category with wider tiles?

## System Statistics
- Staked MKR Percentage
- Number of Voters vs. Total MKR Staked
- Total Votes (Currently Executive Votes vs Polls)
- MKR Gini Coefficient

## Voter Behaviour
- MKR Activeness (30 Day Average)
- MKR Activeness Breakdown
- MKR Responsiveness
- Top Voters (Generic)

## Executives
- Top Executives (Currently ‘Executive Votes’)
- Uncast Executives
- Executive Time to Pass (Currently Time taken for executives)
- MKR Distribution By Executive

## Polls
- Most Voted Polls
- Recent Polls (Currently Top Polls)

Approved design here: https://drive.google.com/file/d/1XhrbyfhQRNHqm7_YAzFjIIeXLeu0UT2V/view

**Comment by tatyanakurinskaya** [comment]
1. Polls section: left should be Most Voted Polls , right - Recent Polls
2. 'Voter Behavior' section is absent
