### ISSUE TITLE
Dashboard: MKR Activeness (30 Day Average)

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#152]
- Graph tile 
- Show the moving average amount of MKR active in the last thirty-day window. 
- Active is defined as voting in an executive vote
- Daily Resolution

1. get all vote events with voter and MKR. 
2. group events by date and by address.
3. sum MKR for each day (make sure we don't count each voter address more than once)
4. TBD

**Comment by mgarciap** [comment]
To be further discussed and defined between @leolower and LFW in a couple weeks
