### ISSUE TITLE
Voting History: Voting history list by address

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#162]
"Voting history of a specific address: Should be displayed in a list format with a searchable/filterable list of polls/executives.  
For each poll/executive a column shows the option the entered address voted for at the time of the poll ending. "

https://docs.google.com/document/d/1xku698E6fp8MVvECJkXYltXHXrG6JrE-Nb-huY5Xiig/edit#heading=h.jp6047svxl29

## Voting History
Displays a list of all polls/executives that address has voted in.

This should be displayed in a list format with a searchable/filterable list of polls/executives. This list should have the following columns:
- Name (As on other lists)
- Type (Poll or Executive)
- Category (Uncategorized by default)
- Status (Open, Passed or Ended)
- Winning Option (Winning option for polls, N/A for executives.)
- Recorded Vote (The option the searched address voted for. ‘No recorded vote’ otherwise. ‘Voted’ for executives.)

For each poll/executive a column shows the option the entered address voted for at the time of the poll ending. Shows 'Didn't Vote' if there is no recorded vote for that address.

**Comment by tatyanakurinskaya** [comment]
1. missing info in table : 

- Category (Uncategorized by default)
- Recorded Vote (The option the searched address voted for. ‘No recorded vote’ otherwise. ‘Voted’ for executives.)

**Comment by leolower** [comment]
`Category` should not be displayed for now as we don't have the information nor the sufficient space. We should add it when it becomes available on the API. There is a ticket for this.

**Comment by matextrem** [comment]
And recorded vote is not necessary since the info displayed are both polls and executives the address voted.

**Comment by tatyanakurinskaya** [comment]
as I understand, in this table we are showing only info if this specified address voted for polls/votes. So for the poll there should be shown the exact option this address voted for - in Recorded vote column
