### ISSUE TITLE
Change tile and list titles to match the UI design

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#185]
Tiles in general should have bold titles, the font, font size and alignment should also match for the tile titles.

Use similar to the "Dashboard" title, just smaller.

**Comment by tatyanakurinskaya** [comment]
please fix 'Description' title for Executive Vote Detail page & Poll Detail page
![Screen Shot 2019-11-04 at 6.37.06 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/1d45f9e9-2409-4370-9512-d0597a4dd79d)
