### ISSUE TITLE
Executive Vote Details: Make exec vote details show new data

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#202]
*The executive details tile should show the following:*
- Spell Address - Address of the proposal spell.
- Start Date - Date on which the proposal was posted.
- Status - Open/Passed
- Time Open - How many days + hours has this been open.
- MKR in Support - # of MKR Staked
- Executed - Yes/No

**Comment by tatyanakurinskaya** [comment]
still reproduced:
1. rename 'Time opened' to 'Time Open'
2. 'MKR in support' to '# of MKR Staked'
