### ISSUE TITLE
Poll, Executive Vote details: wrong view on resizing

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#245]
open Poll details page
make page smaller
make page bigger
and see:
https://drive.google.com/open?id=1DvrNgYX6eVJJl8BOH0Mx35h6W_kbAk1V

**Comment by matextrem** [comment]
It is adapted to a fixed resolution. Desktop, Mobile or tablet . It's pretty difficult to do dynamic resizing due to charts.
