### ISSUE TITLE
Executive Votes list: pagination doesn't allow to open 2nd page

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#248]
open Executive votes list
take a look at pagination ---> it shows as if there is 16 records, but only 10 is shown , no arrow to move to the next page

if select 20 rows, all 16 records are shown

![Screen Shot 2019-11-12 at 6 50 17 PM](https://user-images.githubusercontent.com/863519/68687037-a2498700-057d-11ea-8b46-ef1faf64d510.png)

**Comment by matextrem** [comment]
It couldn't be reproduced.
