### ISSUE TITLE
Polls: not all polls are shown

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#249]
currently https://vote.makerdao.com/polling doesn't show 'Active' polls 

in our app these polls are shown in Polls list and in Polls section on Dashboard, but if take a look at Total Votes section - polls value - per Last day - it shows 55 polls in comparison with polls value per week (58polls):
![Screen Shot 2019-12-23 at 12.45.51 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/80321484-6f3d-4cb5-8540-3ed0e3d5934c)

![Screen Shot 2019-12-23 at 12.45.40 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/e10620f3-2338-40cb-abc2-c4c63f1db4df)

So it seems the issue is that sometimes we show/count active poll, sometimes - not.

+ see **Time opened** value for 'Active' poll: it shows negative value: ![Screen Shot 2019-12-23 at 12.57.55 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/39a3e05e-70de-4873-95a7-6859b47edf0c)

**Comment by matextrem** [comment]
1. It could be related to the fact that we are not counting some polls due to a different contract.
