### ISSUE TITLE
error in console on app opening

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#250]
open app and look at console
Result:
`makerdao.ts:111 Mixed Content: The page at 'https://mkr-gov.netlify.com/' was loaded over HTTPS, but requested an insecure resource 'http://t.est/'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ makerdao.ts:111
Promise.then (async)
(anonymous) @ bundle.esm.js:106
e @ Observable.js:212
value @ Observable.js:290
(anonymous) @ bundle.esm.js:1082
e @ Observable.js:212
value @ Observable.js:290
e.getObservableFromLink @ bundle.esm.js:2043
(anonymous) @ bundle.esm.js:2090
e.fetchRequest @ bundle.esm.js:2089
(anonymous) @ bundle.esm.js:1449
(anonymous) @ tslib.es6.js:208
(anonymous) @ tslib.es6.js:138
(anonymous) @ tslib.es6.js:111
s @ tslib.es6.js:88
e.fetchQuery @ bundle.esm.js:1387
t.setVariables @ bundle.esm.js:397
t.setOptions @ bundle.esm.js:372
t.updateObservableQuery @ react-hooks.esm.js:272
t.execute @ react-hooks.esm.js:134
(anonymous) @ react-hooks.esm.js:494
(anonymous) @ react-hooks.esm.js:447
f @ react-hooks.esm.js:493
h @ react-hooks.esm.js:511
Pa @ index.tsx:30
Uo @ react-dom.production.min.js:3364
ma @ react-dom.production.min.js:3840
Zs @ react-dom.production.min.js:6113
Ks @ react-dom.production.min.js:5101
zs @ react-dom.production.min.js:4958
Ms @ react-dom.production.min.js:4817
(anonymous) @ react-dom.production.min.js:2543
t.unstable_runWithPriority @ scheduler.production.min.js:338
hi @ react-dom.production.min.js:2513
vi @ react-dom.production.min.js:2538
yi @ react-dom.production.min.js:2528
Xs @ react-dom.production.min.js:5934
t.unstable_runWithPriority @ scheduler.production.min.js:338
hi @ react-dom.production.min.js:2513
Gs @ react-dom.production.min.js:5906
(anonymous) @ react-dom.production.min.js:5549
F @ scheduler.production.min.js:195
L @ scheduler.production.min.js:262
O @ scheduler.production.min.js:97
Show 14 more frames
makerdao.ts:183 Error fetching data for poll with ID 11 from http://t.est
test-poll-josh-mike.com/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
makerdao.ts:183 Error fetching data for poll with ID 8 from https://test-poll-josh-mike.com
poll-poll-poll.com/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
makerdao.ts:183 Error fetching data for poll with ID 9 from https://poll-poll-poll.com`

**Comment by matextrem** [comment]
Done. Some errors are logged to have more information.
