### ISSUE TITLE
Dashboard: Uncasted Executives/ Top Voters/ Top Executives modal: Display Source address in full

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#259]
open app
click View All in Uncasted Executives/Top Voters / Top Executives tile
Exp.result: it would be good to show Source in full
![Screen Shot 2019-11-18 at 5 54 02 PM](https://user-images.githubusercontent.com/863519/69063028-d7961f00-0a2c-11ea-8b4c-d6e3504d0bc0.png)

**Comment by matextrem** [comment]
It would be a nice to have. Not necessary for this version.
