### ISSUE TITLE
Executive Votes: when Hat is open, it is not shown when filter by Open

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#260]
open app 
go to Executive votes page:
filter Status column by 'Open' status
currently Hat record is open but it is not shown when filter by Open

see the same for passed(closed) status

Exp.result: I think that when filter by Open/ Passed, Hat record  should be shown as well depending on status of this vote

![Screen Shot 2019-11-18 at 6 04 07 PM](https://user-images.githubusercontent.com/863519/69063743-0eb90000-0a2e-11ea-93d6-f387de841ad5.png)
![Screen Shot 2019-11-18 at 6 04 11 PM](https://user-images.githubusercontent.com/863519/69063744-0eb90000-0a2e-11ea-964c-ca7a891a2750.png)
![Screen Shot 2019-11-18 at 6 04 19 PM](https://user-images.githubusercontent.com/863519/69063746-0eb90000-0a2e-11ea-91d5-8268ed12fe98.png)

**Comment by matextrem** [comment]
If Hat is open it is filter by hat. Open are for those which are not the Hat or the hat is not active.
