### ISSUE TITLE
Dashboard: Executive Votes - Time Taken To Pass is wrong

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#261]
currently, there are 5 open executive votes, the older one started on 06 May 19
![Screen Shot 2019-11-18 at 6 17 01 PM](https://user-images.githubusercontent.com/863519/69064728-ac60ff00-0a2f-11ea-907a-2a990da065ee.png)

but Executive Votes - Time Taken To Pass shows 27days as the longest 
![Screen Shot 2019-11-18 at 6 17 55 PM](https://user-images.githubusercontent.com/863519/69064819-cb5f9100-0a2f-11ea-8682-d1c2a636edbf.png)

**Comment by matextrem** [comment]
The metric is only for passed executives.
