### ISSUE TITLE
Different MKR Participation in Dashboard-Most Voted Polls and Polls list

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#262]
![Screen Shot 2019-11-18 at 6 25 04 PM](https://user-images.githubusercontent.com/863519/69065536-fb5b6400-0a30-11ea-8723-fd8bf3d9719c.png)
![Screen Shot 2019-11-18 at 6 25 00 PM](https://user-images.githubusercontent.com/863519/69065537-fb5b6400-0a30-11ea-82fb-f22a465fb45e.png)

**Comment by matextrem** [comment]
It couldn't be reproduced.

**Comment by tatyanakurinskaya** [comment]
NaN % is shown in Dashboard, but on Polls list there is a percentage value:
dashboard:
![Screen Shot 2019-12-31 at 11 57 58 AM](https://user-images.githubusercontent.com/863519/71616005-1a6b1b00-2bc5-11ea-8ed9-42f370b7c57d.png)

polls list:
![Screen Shot 2019-12-31 at 11 59 34 AM](https://user-images.githubusercontent.com/863519/71616001-1808c100-2bc5-11ea-919b-cd13e60f708d.png)

**Comment by matextrem** [comment]
Fixed in M9 - Feedback
