### ISSUE TITLE
Poll Details: 'Time opened' is wrong for open poll

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#278]
open app
go to Polls
open poll which isn't ended: 
![Screen Shot 2019-12-09 at 2 45 39 PM](https://user-images.githubusercontent.com/863519/70433400-b4421b00-1a92-11ea-9063-c2023dd33330.png)

**Comment by matextrem** [comment]
It couldn't be reproduced.

**Comment by tatyanakurinskaya** [comment]
fixed
