### ISSUE TITLE
Dashboard -> Total Votes: wrong number of polls when choose show 'last day'

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#281]
open app and see in Dashboard
Total Votes graph: select 'Last day':  Polls shows value = 48 as the latest: 
![Screen Shot 2019-12-09 at 4 18 46 PM](https://user-images.githubusercontent.com/863519/70438873-d4c4a200-1a9f-11ea-8551-eaaafde26627.png)

but if select Last week: Polls shows value = 51 as the latest
![Screen Shot 2019-12-09 at 4 18 36 PM](https://user-images.githubusercontent.com/863519/70438965-09d0f480-1aa0-11ea-821f-2784e078cd0d.png)

Polls list has 51 records

**Comment by matextrem** [comment]
Not be able to reproduce it. It seems it works.
