### ISSUE TITLE
Polls with links to github.com don't appear on the list

### ISSUE THREAD

**Issue by leolower** [protofire/maker-governance-dashboard#293]
Rewrite URLs like:
https://github.com/makerdao/community/blob/master/governance/polls/Activate%20the%20Governance%20Security%20Module.md

into: 

https://raw.githubusercontent.com/makerdao/community/master/governance/polls/Activate%20the%20Governance%20Security%20Module.md

**Comment by tatyanakurinskaya** [comment]
1. it requires too much to load Polls list and sometimes it doesn't load
![Screen Shot 2019-12-17 at 3.45.27 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/307491c0-fa0c-4ce0-aa38-a7a278132283)

2. when it is loaded, there is no link (but mouse's state is changed as if there is a link) - seen in Most Voted Polls section

+ link in full view of Most Voted Polls directs to Polls Details page <--- is it expected?

**Comment by matextrem** [comment]
1. It is a weight process, so it takes to much time to load, but the info is cached then to get a faster reaload.
2. I fixed that in https://github.com/protofire/maker-governance-dashboard/pull/305
