### ISSUE TITLE
Dashboard: wrong view of MKR Activeness Breakdown modal when no records found on filtering

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#295]
open app
go to Dashboard -> MKR Activeness Breakdown
click View All
filter by Period - use '72' ---> no records are shown : 
![Screen Shot 2019-12-13 at 6 20 35 PM](https://user-images.githubusercontent.com/863519/70810733-57699c00-1dd5-11ea-8973-a29457c523af.png)

click icon to open filtering modal : 
![Screen Shot 2019-12-13 at 6 18 47 PM](https://user-images.githubusercontent.com/863519/70810727-53d61500-1dd5-11ea-8c36-f82cb1bbfe10.png)

**Comment by matextrem** [comment]
It shouldn't be filtered. We need to hide this filter for this column instead.
