### ISSUE TITLE
Poll w/ 36 and 39 ids has the same poll address - it might be the same poll discovered twice

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#316]
see polls https://mkr-gov.netlify.com/poll/36 and https://mkr-gov.netlify.com/poll/39

Poll address is the same, Start Date 09/30/2019 or 10/01/2019 , Time Open is different by 8hours
![Screen Shot 2019-12-24 at 12 46 01 PM](https://user-images.githubusercontent.com/863519/71407231-8987c300-264b-11ea-827d-fe368678079a.png)
![Screen Shot 2019-12-24 at 12 46 55 PM](https://user-images.githubusercontent.com/863519/71407233-8bea1d00-264b-11ea-975b-04b9eebdcb51.png)

I suspect that this is the same poll, but by some reasons it's discovered by two different polls

**Comment by matextrem** [comment]
I am not be able to reproduce it.

![image.png](https://images.zenhubusercontent.com/5d6690c00f6aff27b640a832/a3b59d2e-8cb9-4655-87bc-d0474791a28c)

**Comment by matextrem** [comment]
They have the same address because polls belongs to the same PollingEmitter contract. But they are actually different polls.

**Comment by tatyanakurinskaya** [comment]
but https://vote.makerdao.com/polling has only one poll with such name 
![Screen Shot 2020-01-14 at 12 19 19 PM](https://user-images.githubusercontent.com/863519/72330779-27f5ca00-36c8-11ea-86fe-5fda2e5e1fb9.png)

**Comment by matextrem** [comment]
That's why I say they are different. If I query the subgraph I get two different polls (with id 36 and 39)

**Comment by tatyanakurinskaya** [comment]
@matextrem ok, but is it possible that for poll with id = 39 'MKR Count By Option' show 0 value for the whole graph, but 'Vote Count By Option'=3 for Yes option ?
