### ISSUE TITLE
Changing Theme From Either Dark or Light Make You Switch to Mobile Version

### ISSUE THREAD

**Issue by Sirlupinwatson1** [protofire/maker-governance-dashboard#318]
###  In the Forum :  

_MakerDAO  user interface,_  Ⓜ️

 https://forum.makerdao.com/u/sirlupinwatson1/preferences/interface

 ----------------------------

**When you try to change your theme interface, from dark or light to 1 of those,** 
**it does not give you the time to save unless you are fast enough to save,**
**turn out to this page here see picture.**

> This Look to me the mobile version

------------------------------

-    _On Windows 10 Pro 1809_   _Type_ **64**
 
 

---------------------------------------------------------------------------------------------------------------

![Makermobile](https://user-images.githubusercontent.com/55941045/71562413-0ea91880-2a4e-11ea-88e3-53ec32847fc2.png)

--------------------------------

<img width="100" height="50" class="irc_mi" alt="Résultats de recherche d'images pour «&nbsp;github&nbsp;»" src="https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2016/11/github-image-796x418.png">

**Comment by LongForWisdom** [comment]
@Sirlupinwatson1 This is not the correct place to raise issues about the forum. This github concerns the development of the governance dashboard located at mkrgov.science.

**Comment by Sirlupinwatson1** [comment]
> @Sirlupinwatson1 This is not the correct place to raise issues about the forum. This github concerns the development of the governance dashboard located at mkrgov.science.

### @LongForWisdom  Sorry about that. I just realize it.
