### ISSUE TITLE
Voter History Screen - Top right column heading is ‘Winning Option’ It should be ‘Voted Option’

### ISSUE THREAD

**Issue by matextrem** [protofire/maker-governance-dashboard#325]

**Comment by LongForWisdom** [comment]
I don't think this deserves the enhancement label, it's a bug. 

My reasoning:
- The column is showing the option for which the searched address voted for in that poll/executive.
- The winning option of that poll/executive can be different from what that address voted for.
- This could easily lead to an incorrect interpretation of the information being shown and a negative user experience.
