### ISSUE TITLE
MKR Activeness Breakdown is wrong, 'last year' value can't be less than 'last 3 months', 'last month' value

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#333]
open app
go to Dashboard and see MKR Activeness Breakdown widget:
![Screen Shot 2020-01-13 at 1.47.13 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/40e4925b-9a94-4e28-8e2b-d5139ceca1c0)

**Comment by matextrem** [comment]
It could be less than the others because it is an average according to the time window. Anyway, we need to discuss this functionality with MakerDAO again so it needs to be updated and we will hide this for production by now.
