### ISSUE TITLE
Initially polls list shows 77 records and as soon as all data is loaded, only 68 is left

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#335]
open app
go to Polls page
see while it is loaded: ![Screen Shot 2020-01-13 at 3.13.18 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/598f0209-f99f-48ab-8b27-7d7a45b13cf1)
as soon as data is loaded, 68 records are shown:
![Screen Shot 2020-01-13 at 3.15.34 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/0199118e-cbad-48c2-bfe3-2d344e8d0669)

**Comment by matextrem** [comment]
That's because there are some 'Test polls' with fake data, but then we filter this to the right polls.
