### ISSUE TITLE
a lot of errors in console

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#337]
open app and see in console
Result: ![Screen Shot 2020-01-13 at 3.21.00 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/cf7a490d-a083-4dbd-8a5a-d525f127f861)

**Comment by matextrem** [comment]
We need to throw exceptions to get more info about errors and so on. Anyway, they are only shown in our staging server.
