### ISSUE TITLE
Poll Details: Time opened shows  '-2hours'

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#339]
open app
go to Polls page
open poll details page for open poll
Result: ![Screen Shot 2020-01-13 at 5.56.50 PM.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/eaafe8e7-951d-45c9-872d-66a4aad89e49)

**Comment by matextrem** [comment]
I am not be able to reproduce it.

![image.png](https://images.zenhubusercontent.com/5d6690c00f6aff27b640a832/a3b59d2e-8cb9-4655-87bc-d0474791a28c)

**Comment by tatyanakurinskaya** [comment]
I opened this poll near 6pm Minsk time and based on your comment to this ticket, you did it near 10pm Minsk time (if you added comment right after checking), so the difference is 4hours, but Time opened shows only '2hours' for you.
Currently I see positive time like '15hours'. Perhaps, issue exists when open Poll Details somewhere at the start
