### ISSUE TITLE
No data for 'Total MKR Supply' after 13th Jan. Also shows as 'NaN' when highlighted.

### ISSUE THREAD

**Issue by LongForWisdom** [protofire/maker-governance-dashboard#345]
![image](https://user-images.githubusercontent.com/53664591/72365752-c007a980-36f0-11ea-84bd-438e96f52deb.png)

See image above. Is this caused by the recent MKR burn?

**Comment by LongForWisdom** [comment]
I have not tested the live dashboard.

**Comment by matextrem** [comment]
I am not able to reproduce the error. Can you try it now?

**Comment by LongForWisdom** [comment]
Does not appear on the 'Daily' scale, but does appear on each of the other scales (Yearly, Monthly, Weekly.) Tested in both live and staging dashboard.

**Comment by LongForWisdom** [comment]
Note the issue only shows in the label when highlighting after the end of the 'Total Staking' metric.  I think the major issue is that it is not correctly showing data after the 13th of January (probably when the total supply was burned.) So fix the data and the label should be fine.
