### ISSUE TITLE
Polling Results differ from vote.makerdao.com

### ISSUE THREAD

**Issue by LongForWisdom** [protofire/maker-governance-dashboard#365]
The results differ between the two dashboards:
https://mkrgov.science/poll/123 
https://vote.makerdao.com/polling-proposal/qmc2ebl5rbvdq3vcgypyhjshwqakxw9rwwowrvzulpnmho

Mkrgov.science states that 16% won, whereas vote.makerdao.com states that 12% won.

**Comment by jiecut42** [comment]
Bug is also visible for the other polls, just that it didn't affect the outcome.

Some double counting occured for the 17k MKR votes to show up as 34k MKR votes.

**Comment by leolower** [comment]
Fixed here: https://github.com/protofire/maker-governance-dashboard/pull/366
