### ISSUE TITLE
Dashboard: some months are missing on full view graph

### ISSUE THREAD

**Issue by tatyanakurinskaya** [protofire/maker-governance-dashboard#78]
open Dashboard
open full view of graph: Number of voters vs Total MKR staked

![Screen Shot 2019-10-09 at 12 40 44 PM](https://user-images.githubusercontent.com/863519/66470895-2302f800-ea93-11e9-87ba-ff21ce0c4f2c.png)

**Comment by matextrem** [comment]
It is for responsiveness, you could see all the series by hover on each column.

**Comment by tatyanakurinskaya** [comment]
fixed
